### ISSUE TITLE
疑问？

### ISSUE THREAD

**Issue by JohnnyTing** [Programming-With-Love/Programming-With-Love-Profile#1]
这个仓库主要用于做什么呢？

**Comment by BoynChan** [comment]
老哥稳 刚提问 readme就更新了

**Comment by AdlerED** [comment]
该仓库主要用于声明组织的守则，督促大家在GitHub友善、积极的互动:smile:

**Comment by AdlerED** [comment]
Closed

**Comment by 88250** [comment]
Closed @InkDP

**Comment by InkDP** [comment]
？？？？？？？


 
---原始邮件---
发件人: "D"<notifications@github.com&gt;
发送时间: 2019年10月9日 16:55:17
收件人: "Programming-With-Love/Programming-With-Love-Profile"<Programming-With-Love-Profile@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"墨殇"<1576962841@qq.com&gt;;
主题: Re: [Programming-With-Love/Programming-With-Love-Profile] 疑问？ (#1)



Closed @InkDP
